global:
  scrape_interval: 15s  # cada cuánto recolecta métricas

scrape_configs:
  - job_name: "spring-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8085"]
